### PR TITLE
Updated to 1.18.1

### PR DESCRIPTION
**Pull request by emilyastranova**

### CODE REVIEW

**Comment by emilyastranova** [comment]
You may want to create another branch for 1.18, thats how my local version is

**Comment by emilyastranova** [comment]
image

**Comment by emilyastranova** [comment]
Added requested feature from #6 
image

**Comment by Cynosphere** [comment]
The 1.17 version works fine without issues on 1.18. Unless theres proof that this one mapping change causes crashes, its entirely redundant.

**Comment by exaskye** [comment]
This is a broken PR (it includes an unrelated commit due to a bad merge) and is unnecessary; as Cynosphere said the 1.17 version of Drogtor works fine on 1.18 as this part of the game didn't change.

You're free to open a new PR that is only the new feature you added.

**Comment by emilyastranova** [comment]
My apologies, it wasn't working for me but it may have been another mod interfering. I went on an absolute frenzy updating every mod on our server. Feel free to cherry pick that code for the console logging, I don't think there's a way to only choose that commit but you may take that code from the files themselves

**Pull request closed without merging**
